/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.company.visao.outros.funcionarios;

/**
 *
 * @author elymar.8221
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        miCadastro = new javax.swing.JMenu();
        miCadastroCinema = new javax.swing.JMenuItem();
        miCadastroSala = new javax.swing.JMenuItem();
        miCadastroSessao = new javax.swing.JMenuItem();
        miCadastroFilme = new javax.swing.JMenuItem();
        miCadastroGenero = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        miCadastroCliente = new javax.swing.JMenuItem();
        miConsulta = new javax.swing.JMenu();
        miConsultaCinema = new javax.swing.JMenuItem();
        miConsultaSala = new javax.swing.JMenuItem();
        miConsultaSessao = new javax.swing.JMenuItem();
        miConsultaFilme = new javax.swing.JMenuItem();
        miConsultaGenero = new javax.swing.JMenuItem();
        miConsultaIngressos = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        miConsultaCliente = new javax.swing.JMenuItem();
        miConsultaCompra = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DO CINEMA");

        miCadastro.setText("Cadastros");

        miCadastroCinema.setText("Cinema");
        miCadastro.add(miCadastroCinema);

        miCadastroSala.setText("Sala");
        miCadastro.add(miCadastroSala);

        miCadastroSessao.setText("Sessão");
        miCadastro.add(miCadastroSessao);

        miCadastroFilme.setText("Filme");
        miCadastro.add(miCadastroFilme);

        miCadastroGenero.setText("Gênero");
        miCadastro.add(miCadastroGenero);
        miCadastro.add(jSeparator1);

        miCadastroCliente.setText("Cliente");
        miCadastro.add(miCadastroCliente);

        jMenuBar1.add(miCadastro);

        miConsulta.setText("Consultas");

        miConsultaCinema.setText("Cinema");
        miConsulta.add(miConsultaCinema);

        miConsultaSala.setText("Sala");
        miConsulta.add(miConsultaSala);

        miConsultaSessao.setText("Sessão");
        miConsulta.add(miConsultaSessao);

        miConsultaFilme.setText("Filme");
        miConsulta.add(miConsultaFilme);

        miConsultaGenero.setText("Gênero");
        miConsulta.add(miConsultaGenero);

        miConsultaIngressos.setText("Ingressos");
        miConsulta.add(miConsultaIngressos);
        miConsulta.add(jSeparator2);

        miConsultaCliente.setText("Cliente");
        miConsulta.add(miConsultaCliente);

        miConsultaCompra.setText("Compra");
        miConsulta.add(miConsultaCompra);

        jMenuBar1.add(miConsulta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 457, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenu miCadastro;
    private javax.swing.JMenuItem miCadastroCinema;
    private javax.swing.JMenuItem miCadastroCliente;
    private javax.swing.JMenuItem miCadastroFilme;
    private javax.swing.JMenuItem miCadastroGenero;
    private javax.swing.JMenuItem miCadastroSala;
    private javax.swing.JMenuItem miCadastroSessao;
    private javax.swing.JMenu miConsulta;
    private javax.swing.JMenuItem miConsultaCinema;
    private javax.swing.JMenuItem miConsultaCliente;
    private javax.swing.JMenuItem miConsultaCompra;
    private javax.swing.JMenuItem miConsultaFilme;
    private javax.swing.JMenuItem miConsultaGenero;
    private javax.swing.JMenuItem miConsultaIngressos;
    private javax.swing.JMenuItem miConsultaSala;
    private javax.swing.JMenuItem miConsultaSessao;
    // End of variables declaration//GEN-END:variables
}
